# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'windowAv.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_windowaviso(object):
    def setupUi(self, windowaviso):
        windowaviso.setObjectName("windowaviso")
        windowaviso.resize(360, 200)
        windowaviso.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(windowaviso)
        self.buttonBox.setGeometry(QtCore.QRect(-90, 130, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(windowaviso)
        self.label.setGeometry(QtCore.QRect(120, 10, 111, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("img/istockphoto-1165690157-612x612.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(windowaviso)
        self.lineEdit.setGeometry(QtCore.QRect(60, 80, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(windowaviso)
        self.buttonBox.accepted.connect(windowaviso.accept)
        self.buttonBox.rejected.connect(windowaviso.reject)
        QtCore.QMetaObject.connectSlotsByName(windowaviso)

    def retranslateUi(self, windowaviso):
        _translate = QtCore.QCoreApplication.translate
        windowaviso.setWindowTitle(_translate("windowaviso", "Dialog"))
        self.lineEdit.setText(_translate("windowaviso", "Confirma que quiere salir"))
